I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 63, in script
    h "Хэй, босс. Решил проветриться, это круто. Сегодня довольно солнечно, цепляй меня и погнали."
Exception: Sayer 'h' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 63, in script
    h "Хэй, босс. Решил проветриться, это круто. Сегодня довольно солнечно, цепляй меня и погнали."
  File "/tmp/user/Downloads/renpy-7.4.2-sdk/renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "/tmp/user/Downloads/renpy-7.4.2-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'h' is not defined.

Linux-5.10.17-1-lts-x86_64-with-glibc2.2.5
Ren'Py 7.4.2.1292
Girya 1.0
Sat Feb 27 19:19:45 2021
